name: Deploy
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy using ssh
      uses: garygrossgarten/github-action-ssh@release
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        privateKey: ${{ secrets.SSH_PRIVATE_KEY }}
        command: |
          cd /usr/local/bin/QuestoesDeConcursoBot/
          git pull origin main
          systemctl restart tg_questoesdeconcurso
  message:
    needs:
      - deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.8'
    - name: Install Requirements
      run: pip install -r requirements.txt
    - name: Run Novidades
      run: python utils/novidades.py
      env:
        commit_message: ${{ github.event.head_commit.message }}
