name: Deploy
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy using ssh
      uses: garygrossgarten/github-action-ssh@release
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        privateKey: ${{ secrets.SSH_PRIVATE_KEY }}
        command: |
          cd /usr/local/bin/QuestoesDeConcursoBot/
          git pull origin main
          systemctl restart tg_questoesdeconcurso
