name: Yaml lint
on:
  pull_request:

jobs:
  yamllint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Yamllint questoes
      uses: ibiqlik/action-yamllint@v3
      with:
        file_or_dir: questoes/
        config_file: utils/yamllink-conf.yaml
